# Site settings
title: Will'X Blog
SEOTitle: 吴翔的博客 | Will'X Blog
header-img: img/home-bg.jpg
email: willx8@gmail.com
description: "SE@SJTU 会一点C++/Go/Python/C/Java/Scheme 编程/平面设计/美"
keyword: "吴翔, willx8, 吴翔的博客, Will'X Blog, 博客, 个人网站, 技术, 设计"
url: "http://willx8.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"


# SNS settings
RSS: false
weibo_username:     willwhiff
zhihu_username:     wu-ji-ao
github_username:    willx8
#twitter_username:  willx8
facebook_username:  willx8

markdown: redcarpet2
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

    #syntax highlighting
    #syntax-highlighting:
    #  enabled : true
    #  css: syntax.css

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

      ## Duoshuo settings
      #duoshuo_username: willx8
      ## Share component is depend on Comment so we can NOT use share only.
      #duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 5d4781e7d37cd66b26a3a87a2eee32c5
# Google Analytics
ga_track_id: 'UA-73347036-1'            # Format: UA-xxxxxx-xx
ga_domain: willx8.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Enthusiastic about exploring a bigger world. I HATE GFW."
sidebar-avatar: /img/avatar-will.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



    ## Featured Tags
    #featured-tags: true                     # whether or not using Feature-Tags
    #featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Feel free to contact me and appear here.",
        href: "http://myfriend/"
        }
]
